import { useState, useEffect } from "react";
import { Typeahead } from "react-bootstrap-typeahead";
import Head from "next/head";
import wilderAPI from "../services/wilderAPI";
import Wilder from "../components/Wilder";
import Layout from "../components/Layout";
import AddAWilder from "../components/AddAWilder";
import "bootstrap/dist/css/bootstrap.css";
import "react-bootstrap-typeahead/css/Typeahead.css";
import styles from "../styles/Home.module.css";

export default function Home({ wildersStatic, staticSkills }) {
  const [wilders, setWilders] = useState([]);
  const [alltags, setAlltags] = useState([]);
  const [selectedTags, setSelectedTags] = useState([]);

  const tagFilter = (wilder) => {
    if (!selectedTags.length) return true;

    let tagFound = selectedTags.map((tag) => false);
    selectedTags.forEach((tag, tagIndex) => {
      if (wilder.name.includes(tag)) tagFound[tagIndex] = true;
      wilder.skills.forEach((skill) => {
        if (skill.name === tag) tagFound[tagIndex] = true;
      });
    });
    return tagFound.every((tag) => tag === true);
  };

  useEffect(() => {
    setWilders(wildersStatic);
    console.log(wildersStatic);
  }, [wildersStatic]);

  useEffect(() => {
    setAlltags(
      [
        ...staticSkills.map((skill) => skill.name),
        ...wildersStatic.map((wilder) => wilder.name),
      ].sort()
    );
  }, []);

  return (
    <Layout>
      <Head>
        <title>Wilders Book</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.h2Container}>
          <h2>Wilders</h2>{" "}
          <Typeahead
            multiple
            id="tags"
            placeholder="Recherchez un wilder ou un skill"
            onChange={(text) => {
              setSelectedTags(text);
            }}
            options={alltags}
            selected={selectedTags}
          />
        </div>
        <div className={styles.wildersContainer}>
          {wilders &&
            wilders.length > 0 &&
            wilders
              .filter(tagFilter)
              .map((wilder, wilderIndex) => (
                <Wilder
                  key={wilder.id}
                  wilder={wilder}
                  wilderIndex={wilderIndex}
                  staticSkills={staticSkills}
                  wilders={wilders}
                  setWilders={setWilders}
                />
              ))}
          <AddAWilder wilders={wilders} setWilders={setWilders} />
        </div>
      </main>
    </Layout>
  );
}

export async function getStaticProps() {
  let wildersStatic = [];
  let staticSkills = [];

  try {
    wildersStatic = (await wilderAPI.back.get("/wilders")).data;
    staticSkills = (await wilderAPI.back.get(`/skills/`)).data;
  } catch (err) {
    console.error(err);
  }

  return {
    props: {
      wildersStatic,
      staticSkills,
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 10 seconds
    revalidate: 10, // In seconds
  };
}
